name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        run: |
          sudo apt-get update
          sudo apt-get install php php-cli php-xml php-mbstring

      - name: Run PHP tests (usando PHPUnit)
        run: |
          # Si tienes un archivo de pruebas PHP, asegúrate de ejecutar PHPUnit
          # Si ya tienes PHPUnit instalado globalmente, simplemente ejecútalo
          # Si no, puedes descargar PHPUnit de la siguiente manera:
          curl -sS https://phar.phpunit.de/phpunit.phar -o phpunit.phar
          chmod +x phpunit.phar
          ./phpunit.phar --configuration phpunit.xml  # O ajusta el comando si usas otro archivo de configuración

      - name: Run PHP code linter
        run: |
          curl -sS https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o phpcs.phar
          php phpcs.phar --standard=PSR12 src  # Verificar estilo de código PHP
