name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        run: |
          sudo apt-get update
          sudo apt-get install php php-cli php-xml php-mbstring

      - name: Install dependencies (Composer)
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install  # Si usas Composer

      - name: Run PHP tests with PHPUnit
        run: |
          ./vendor/bin/phpunit  # Ejecutar las pruebas de PHP (usando PHPUnit)
        
      - name: Run PHP code linter
        run: |
          curl -sS https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o phpcs.phar
          php phpcs.phar --standard=PSR12 src  # Verificar estilo de código PHP
