

@@ -1,29 +1,29 @@
name: Test 

on: push

jobs:
  test:
	runs-on: ubuntu-latest

   	 steps:
    	  # 1. Checkout del c칩digo
    	  - name: Checkout code
     	   uses: actions/checkout@v4
     	   
     	   
     	   

    	  # 2. Configuraci칩n de PHP
	      - name: Set up PHP
	        run: |
	          sudo apt-get update
	          sudo apt-get install -y php php-cli php-xml php-mbstring
	          
	          
	          
	          
	
	      # 3. Instalar Composer
	      - name: Install Composer
	        run: |
	          curl -sS https://getcomposer.org/installer | php
	          sudo mv composer.phar /usr/local/bin/composer
	          
	          
	          
	
	      # 4. Instalar dependencias de Composer
	      - name: Install dependencies (Composer)
	        run: |
	          composer install
	          
	       
	
	      # 5. Descargar PHPUnit (si no est치 instalado globalmente)
	      - name: Install PHPUnit
	        run: |
	          curl -sS https://phar.phpunit.de/phpunit.phar -o phpunit.phar
	          chmod +x phpunit.phar
	          sudo mv phpunit.phar /usr/local/bin/phpunit
	
	      # 6. Ejecutar las pruebas con PHPUnit
	      - name: Run PHP tests (usando PHPUnit)
	        run: |
	          php phpunit.phar --configuration phpunit.xml  # O simplemente usa "phpunit" si ya 	est치 en el $PATH	
