name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run JS tests
        run: |
          npm test  # Ejecutar pruebas de JavaScript

      # Verificar est치ndares de c칩digo y escaneo de seguridad
      - name: Run code linter
        run: |
          phpcs --standard=PSR12 src  # Verificar estilo de c칩digo PHP
          npm run lint  # Verificar estilo de c칩digo JS/TS
